CREATE TABLE users (
    user_id INTEGER UNSIGNED NOT NULL PRIMARY KEY,
    balance TEXT NOT NULL DEFAULT '0',
    LKOH INTEGER UNSIGNED NOT NULL DEFAULT 0,
    SBER INTEGER UNSIGNED NOT NULL DEFAULT 0,
    GAZP INTEGER UNSIGNED NOT NULL DEFAULT 0,
    VTBR INTEGER UNSIGNED NOT NULL DEFAULT 0
);

CREATE TABLE reg_orders(
    order_id TEXT NOT NULL PRIMARY KEY,
    user_id INTEGER UNSIGNED NOT NULL,
    type TEXT NOT NULL,
    asset TEXT NOT NULL,
    lots INTEGER UNSIGNED NOT NULL DEFAULT 0,
    price TEXT NOT NULL DEFAULT '0',
    status TEXT NOT NULL DEFAULT 'active',
    date DATETIME NOT NULL
);
